services:
  postgres:
    image: postgres:17.4
    container_name: backend-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: menota-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: backend-java
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/menota-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
    volumes:
      - .:/app
      - /root/.m2:/root/.m2  
    ports:
      - "8080:8080"
      - "35729:35729"
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  postgres_data:
