FROM maven:3.9.9-eclipse-temurin-21

WORKDIR /app

COPY pom.xml ./
RUN mvn dependency:go-offline

COPY . .

EXPOSE 35729

ENTRYPOINT ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev", \
     "-Dspring.devtools.restart.enabled=true", \
     "-Dspring.devtools.livereload.enabled=true", \
     "-Dspring-boot.run.fork=false"]
